services:
  ${project_name}:
    build: .
    container_name: ${project_name}
    command: uv run fastapi run app.app:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
